Repository sourabhsikarwar/Scene-Movie-Platform, pull requests merged in 2023-06, with the labels that each got.

#174 refactor: refactor codebase
  src/components/Banner/Banner.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/General.jsx
  src/components/Carousel/Similiar.jsx
  src/components/Carousel/Trending.jsx
  src/components/Navbar/NavLink.jsx
  src/components/Profile.jsx
  src/components/Search.jsx
  src/pages/Home.jsx
  src/pages/Movie.jsx
  yarn.lock
Labels: enhancement, gssoc23, level2

#176 On pressing enter it must logged in / signed-up #168
  src/components/Login.jsx
  src/components/Signup.jsx
Labels: enhancement, gssoc23, level1

#169 final bugs fixed resolved
  src/components/Cards/MovieCard.jsx
  src/components/SavedShows.jsx
  src/context/authContext.js
Labels: bug, gssoc23, level2

#185 Profile Section UI Enhancement done
  package-lock.json
  src/components/Profile.jsx
  yarn.lock
Labels: gssoc23, level1

#188 Website Redirects to Login Page Upon Refresh solved
  src/App.jsx
  src/components/ProtectedRoute.js
  src/context/authContext.js
Labels: bug, gssoc23, level2

#190 Trailer video responsiveness added
  src/components/Banner/MovieBanner.jsx
  src/index.css
Labels: bug, gssoc23, level1

#201 Meta tags added
  public/index.html
  src/components/Navbar/NavLink.jsx
Labels: enhancement, gssoc23, level1

#191 Fixed rendering error in Date of Birth section #187
  src/components/Profile.jsx
Labels: bug, gssoc23, level1

#195 Added key prop
  src/components/Carousel/Trending.jsx
  src/components/Navbar/NavLink.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/Home.jsx
Labels: bug, gssoc23, level1

#209 Alt attributes added
  src/components/Cards/Card.jsx
  src/components/Cards/MovieCard.jsx
  src/components/Favourite.jsx
  src/components/Profile.jsx
  src/components/Ui/Avatar.jsx
  yarn.lock
Labels: bug, gssoc23, level1

#210 Added doc_report issue template
  .github/ISSUE_TEMPLATE/📄-Doc_report.yml
Labels: documentation, gssoc23, level1

#212 Additions in Issue Template done
  .github/ISSUE_TEMPLATE/Documentation.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/styles.yml
Labels: documentation, gssoc23, level1

#214 lazy loading implemented
  src/App.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Cards/Card.jsx
  src/components/Favourite.jsx
  src/components/Footer.jsx
  src/components/Login.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Profile.jsx
  src/components/SavedShows.jsx
  src/components/Signup.jsx
  src/components/Ui/Avatar.jsx
  src/pages/NotFound404.jsx
Labels: enhancement, gssoc23, level3

#227 updating the search functionality
  src/components/Search.jsx
Labels: bug, enhancement, gssoc23, level2

#234 Home page navigation after signing up added
  src/components/Signup.jsx
Labels: bug, gssoc23, level1

#211 Toast messages added
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login.jsx
  src/context/authContext.js
  yarn.lock
Labels: enhancement, gssoc23, level2

#235 added country code to number input
  package-lock.json
  package.json
  src/components/Signup.jsx
Labels: enhancement, gssoc23, level2

#244 changed firebase error messages to the custom one
  src/components/Login.jsx
  yarn.lock
Labels: bug, gssoc23, level1

#247 dependabot.yml file is added
  .github/dependabot.yml
Labels: enhancement, gssoc23, level2

#253 Fixed Phone Number
  src/components/Signup.jsx
Labels: bug, gssoc23, level2

#259 Added scroll to top button
  src/App.jsx
  src/components/ScrollToTop.jsx
  tailwind.config.js
Labels: enhancement, gssoc23, level2

#266 Added light mode functionality
  public/index.html
  src/App.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/Similiar.jsx
  src/components/Carousel/Trending.jsx
  src/components/Footer.jsx
  src/components/Login.jsx
  src/components/Navbar/NavLink.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Profile.jsx
  src/components/SavedShows.jsx
  src/components/Search.jsx
  src/components/Signup.jsx
  src/components/Ui/Avatar.jsx
  src/index.css
  src/pages/Home.jsx
  src/pages/NotFound404.jsx
  src/style.js
  tailwind.config.js
Labels: enhancement, gssoc23, level3

#254 feat: add server
  server/.gitignore
  server/depoly.yml
  server/index.js
  server/package.json
  server/routes/movies.js
  src/components/Movies.jsx
Labels: enhancement, gssoc23, level3

#264 Remove from favourites after subsequent clicks on favourite button
  src/components/Cards/MovieCard.jsx
Labels: enhancement, gssoc23, level2

#271 Fixed Profile
  src/context/authContext.js
Labels: enhancement, gssoc23, level2

#272 Fixed the issue of watch and like button!
  src/components/Banner/MovieBanner.jsx
Labels: bug, gssoc23, level1

#262 added navbar closing when clicking on any nav links
  src/components/Navbar/NavLink.jsx
  src/components/Navbar/Navbar.jsx
Labels: gssoc23, level2

#275 Lighthouse score improved
  README.md
  src/App.jsx
  src/assets/image/avatar.jpg
  src/assets/image/avatar.webp
  src/assets/image/bg.webp
  src/assets/image/bg1.png
  src/assets/image/bg1.webp
  src/assets/image/bg2.jpg
  src/assets/image/bg2.webp
  src/assets/image/hide.png
  src/assets/image/hide.webp
  src/assets/image/logo2.png
  src/assets/image/logo2.webp
  src/assets/image/notfound.png
  src/assets/image/notfound.webp
  src/assets/image/show.png
  src/assets/image/show.webp
  src/assets/image/slide.png
  src/assets/image/slide.webp
  src/assets/image/star.png
  src/assets/image/star.webp
  src/components/Cards/Card.jsx
  src/components/Cards/MovieCard.jsx
  src/components/Carousel/General.jsx
  src/components/Carousel/Similiar.jsx
  src/components/Carousel/Trending.jsx
  src/components/Favourite.jsx
  src/components/Favourites.jsx
  src/components/Footer.jsx
  src/components/Login.jsx
  src/components/Movies.jsx
  src/components/Navbar/NavLink.jsx
  src/components/Navbar/Navbar.jsx
  src/components/OAuth.jsx
  src/components/Profile.jsx
  src/components/SavedShows.jsx
  src/components/Search.jsx
  src/components/Signup.jsx
  src/components/Ui/Avatar.jsx
  src/pages/Home.jsx
  src/pages/NotFound404.jsx
Labels: enhancement, gssoc23, level3

#284 Added the passwordReset page
  src/App.jsx
  src/components/Login.jsx
  src/components/Reset.jsx
  src/components/Signup.jsx
Labels: enhancement, gssoc23, level3

#280 Update profile added
  src/components/Profile.jsx
  src/context/authContext.js
Labels: enhancement, gssoc23, level2

#296 logo redirecting to home
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/Similiar.jsx
  src/components/Carousel/Trending.jsx
  src/components/Movies.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Pagination.jsx
  src/pages/Home.jsx
Labels: bug, gssoc23, level2

#304 Fixed : issue #283
  package-lock.json
  package.json
  src/components/Footer.jsx
  yarn.lock
Labels: enhancement, gssoc23, level2

#316 feat: add genre to the favourites
  src/components/Cards/MovieCard.jsx
  src/components/SavedCards.jsx
  src/components/SavedShows.jsx
  yarn.lock
Labels: enhancement, gssoc23, level3

#312 About us page
  src/App.jsx
  src/components/AdminAbout.jsx
  src/components/Contributor.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/About.jsx
Labels: enhancement, gssoc23, level3

#309 #308 issue Resolved
  .gitignore
  server/.gitignore
Labels: bug, gssoc23, level1

#311 fix white space
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/Trending.jsx
Labels: bug, gssoc23, level1
