Repository sourabhsikarwar/Scene-Movie-Platform, pull requests merged in 2023-08, with the labels that each got.

#432 Fixed Search bar bug
  src/components/Search.jsx
Labels: gssoc23, level1

#493 Tv reviews
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level2

#495 added dropdown collapsing
  src/components/Navbar/NavLink.jsx
  src/components/Navbar/Navbar.jsx
Labels: gssoc23, level1

#502 added toggle btn for tv series and movies
  src/index.css
  src/pages/Home.jsx
Labels: gssoc23, level2

#479 popular genre cards ui
  src/components/Cards/GenreCard.jsx
  src/components/Carousel/Genre.jsx
Labels: gssoc23, level2

#505 Added Seasons and episodes
  src/components/Banner/TvBanner.jsx
  src/index.css
Labels: gssoc23, level2

#444 404 Error Page Improved
  src/index.css
  src/pages/NotFound404.jsx
Labels: gssoc23, level2

#507 fix: improperly visible go to top button on footer ⚒️
  src/components/ScrollToTop.jsx
Labels: gssoc23, level1

#512 search Feature Added #503
  src/components/Contributor.jsx
Labels: gssoc23, level2

#514 Bug fix 504 Profile alignment issue
  src/components/Profile.jsx
  src/pages/About.jsx
Labels: gssoc23, level1

#518 added airing today
  src/components/Cards/MovieCard.jsx
  src/components/Carousel/Trending.jsx
  src/pages/Home.jsx
Labels: gssoc23, level2

#526 fix: vertical misalignment of nav bar on desktop device ⚒️✨
  src/components/Navbar/Navbar.jsx
Labels: gssoc23, level2

#525 removed tv shows link from footer
  src/components/Footer.jsx
Labels: gssoc23, level1

#532 Codebase refactor
  src/components/Banner/CommonBanner.jsx
  src/components/Banner/Details.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Banner/TvBanner.jsx
  src/pages/Home.jsx
Labels: gssoc23, level2

#537 bug fix issue chatbot #513
  src/index.css
Labels: gssoc23, level1

#551 refactor: feature request issue template 🔧 ✨
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/🪶-feature-request.md
Labels: gssoc23, level1

#552 refactor: documentation issue template 🔧 ✨
  .github/ISSUE_TEMPLATE/Documentation.yml
  .github/ISSUE_TEMPLATE/📄-Doc_report.yml
Labels: gssoc23, level1

#549 Added Videos
  src/components/Banner/MovieBanner.jsx
  src/index.css
Labels: gssoc23, level2

#533 Content rating
  src/components/Banner/CommonBanner.jsx
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level1

#586 Bug fix 547
  src/components/Banner/MovieBanner.jsx
  src/index.css
Labels: gssoc23, level1

#598 fixed card onclick
  src/components/Cards/GenreCard.jsx
  src/components/Cards/MovieCard.jsx
Labels: gssoc23, level1

#594 correct release date
  src/components/Cards/Card.jsx
Labels: gssoc23, level1

#595 Added Tv trailer
  src/components/Banner/CommonBanner.jsx
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level2

#596 refactored movie/tv pages
  src/components/Banner/CommonBanner.jsx
  src/components/Banner/Details.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level3

#602 fixed
  src/components/Banner/CommonBanner.jsx
Labels: gssoc23, level2

#605 added episode page
  src/App.jsx
  src/components/Banner/Episode.jsx
  src/components/Banner/TvBanner.jsx
  src/pages/Episode.jsx
Labels: gssoc23, level3

#611 fixed
  src/components/ScrollToTop.jsx
Labels: gssoc23, level2

#603 handled empty data fields
  src/components/Banner/CommonBanner.jsx
  src/components/Banner/Details.jsx
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level2

#610 Tv cast
  src/App.jsx
  src/components/Banner/Episode.jsx
Labels: gssoc23, level2
