Repository sourabhsikarwar/Scene-Movie-Platform, pull requests merged in 2023-07, with the labels that each got.

#380 Added auto scroll to top feature
  src/components/Login.jsx
  src/components/Reset.jsx
  src/components/Signup.jsx
Labels: bug, gssoc23, level1

#382 fixed movie routing issue
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/Similiar.jsx
Labels: gssoc23, level2

#369 Padding to footer top added
  src/components/Footer.jsx
Labels: gssoc23, level1

#396 About us page made responsive
  src/components/AdminAbout.jsx
  src/pages/About.jsx
  src/style.js
Labels: gssoc23, level2

#394 Added share functionality to the card
  package.json
  src/components/Cards/MovieCard.jsx
Labels: enhancement, gssoc23, level2

#424 feat: add routing in frontend to sync with backend
  package.json
  server/routes/movies.js
  src/components/Banner/Banner.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/General.jsx
  src/components/Carousel/Similiar.jsx
  src/components/Carousel/Trending.jsx
  src/components/Movies.jsx
  src/components/SavedCards.jsx
  src/components/Search.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
Labels: gssoc23, level3

#335 Navbar changes
  src/components/Navbar/Navbar.jsx
Labels: bug, gssoc23, level2

#426 Added aria attributes to login and signup forms
  src/components/Login.jsx
  src/components/Signup.jsx
Labels: gssoc23, level1

#430 feat: convert into fetch api from axios
  server/routes/movies.js
  src/components/Banner/Banner.jsx
  src/components/Banner/MovieBanner.jsx
  src/components/Carousel/General.jsx
  src/components/Carousel/Similiar.jsx
  src/components/Carousel/Trending.jsx
  src/components/SavedCards.jsx
  src/components/Search.jsx
  src/helper/fetchData.js
  src/pages/Home.jsx
Labels: gssoc23, level3

#445 Added accessibility to footer
  src/components/Footer.jsx
Labels: gssoc23, level1

#364 fixed hidden banner buttons on mobile
  src/components/Banner/Banner.jsx
Labels: gssoc23, level1

#458 Movie page UI optim
  src/components/Banner/MovieBanner.jsx
  src/index.css
Labels: gssoc23, level2

#460 added movie details section
  src/components/Banner/MovieBanner.jsx
Labels: gssoc23, level2

#463 Added chatbot functionality
  package.json
  public/index.html
  src/App.jsx
  src/components/SavedShows.jsx
Labels: enhancement, gssoc23, level3

#474 added movie reviews
  src/components/Banner/MovieBanner.jsx
  src/index.css
Labels: gssoc23, level3

#435 Show password icon
  src/components/Login.jsx
  src/components/Signup.jsx
Labels: gssoc23, level1

#433 circleRating and date added
  package.json
  src/components/Cards/MovieCard.jsx
  src/components/circleRating/CircleRating.jsx
  src/components/circleRating/style.css
Labels: gssoc23, level2

#470 feat: server deployment
  server/depoly.yml
  server/index.js
  server/package.json
  server/routes/movies.js
  server/vercel.json
Labels: gssoc23, level3

#466 added Mobile view movies and tv shows display
  src/components/Navbar/NavLink.jsx
  src/components/Navbar/Navbar.jsx
Labels: gssoc23, level2

#481 added slider on homepage
  src/components/Banner/Banner.jsx
Labels: gssoc23, level3

#471 fixed movie details alignment over banner
  src/components/Banner/MovieBanner.jsx
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level1

#490 Added Tv shows details
  src/components/Banner/TvBanner.jsx
Labels: gssoc23, level2
