Repository sourabhsikarwar/Scene-Movie-Platform, pull requests merged in 2023-05, with the labels that each got.

#50 Fixes #11 Signup button
  src/components/Navbar/Navbar.jsx
Labels: bug, gssoc23, level1

#68 Added OnClick functionality to logo
  src/components/Navbar/Navbar.jsx
Labels: good first issue, gssoc23, level1

#91 [PR for #76]: Created Templates to add new feature, report bugs and pull requests.
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
  .github/ISSUE_TEMPLATE/🪶-feature-request.md
  .github/pull_request_template.md
Labels: documentation, gssoc23, level1

#107 Scroll bar
  package-lock.json
  src/index.css
Labels: enhancement, gssoc23, level2

#112 confirm password added in Signup page
  src/components/Signup.jsx
Labels: enhancement, gssoc23, level2

#132 Footer Icon navigate to Home
  src/components/Footer.jsx
Labels: good first issue, gssoc23, level1

#137 Movie Trailer Added
  package-lock.json
  package.json
  src/App.jsx
  src/components/Banner/MovieBanner.jsx
  yarn.lock
Labels: enhancement, gssoc23, level2

#152 removed login page stickiness
  src/components/Login.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Signup.jsx
  yarn.lock
Labels: bug, enhancement, gssoc23, level2

#149 Update README.md
  README.md
Labels: documentation, gssoc23, level1

#146 Updated the card section
  src/assets/image/star.png
  src/components/Cards/Card.jsx
  src/components/Cards/MovieCard.jsx
Labels: enhancement, gssoc23, level2

#155 Genres "Music & War" are added
  src/components/Navbar/Links.js
Labels: enhancement, gssoc23, level2

#160 heart button functionality added on the movie cards displayed on home page
  package-lock.json
  package.json
  src/App.jsx
  src/components/Cards/MovieCard.jsx
  src/components/Favourite.jsx
  src/components/SavedShows.jsx
  src/components/Ui/Avatar.jsx
  src/components/styles.css
  src/context/authContext.js
  src/pages/Home.jsx
  yarn.lock
Labels: enhancement, gssoc23, level3
